OPENAI_API_KEY = "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"
EMAIL_PASSWORD = ""
LLAMA_API_KEY = "llx-PBjJp5kRowb8kmzpV7gTMLdKoxPdbMiPAJE24T3TzlNfmOBY"